export const professions = [
  "Financial Advisor",
  "Data Scientist",
  "Electrical Engineer",
  "Civil Engineer",
  "Food Scientist",
  "Maintenance & Repair Worker",
  "Bus Driver",
  "Automotive Mechanic",
  "Receptionist",
  "Systems Analyst",
  "Housekeeper",
  "Urban Planner",
  "Teacher Assistant",
  "Human Resources Assistant",
  "Construction Manager",
  "Registered Nurse",
  "Web Developer",
  "Librarian",
  "Middle School Teacher",
];
